services:
  client:
    container_name: client
    image: client/v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - mern
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  client:
    name: client
